---
specfile_path: sen.spec
jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-all
- job: tests
  trigger: pull_request
  targets:
  - fedora-all
- job: propose_downstream
  trigger: release
  dist_git_branches: fedora-all
